-- INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao)
Use FNAC;
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1005,'EDM','David Bowie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1006,'Indie Rock','Kings of Leon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1007,'Indie Rock','Paloma Faith','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1008,'Rock','Eric Clapton & Cream','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1009,'Jazz','Fleetwood Mac','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1010,'EDM','Red Hot Chili Peppers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1011,'Metal','Stereophonics','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1012,'Pop','Paul Young','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1013,'Pop','Whitney Houston','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1014,'Jazz','Blur','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1015,'Hip Hop','Bruce Springsteen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1016,'Pop','George Michael','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1017,'Rock','Dua Lipa','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1018,'Rock','Eagles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1019,'Rock','Duran Duran','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1020,'Hip Hop','Bryan Adams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1021,'Pop','David Guetta','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1022,'Pop','Twenty One Pilots','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1023,'Techno','The Seekers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1024,'Blues','Johnny Cash','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1025,'Techno','Andy Williams','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1026,'Pop','Wham!','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1027,'Blues','London Grammar','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1028,'Rock','Ariana Grande','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1029,'EDM','Blondie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1030,'Techno','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1031,'Blues','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1032,'Pop','Madness','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1033,'Rock','Green Day','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1034,'Metal','P!nk','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1035,'EDM','Electric Light Orchestra','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1036,'Hip Hop','M People','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1037,'Pop','Texas','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1038,'Pop','Christina Aguilera','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1039,'EDM','Portishead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1040,'Techno','Coldplay','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1041,'Rock','Rihanna','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1042,'Indie Rock','Drake','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1043,'Pop','UB40','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1044,'Jazz','Neil Diamond','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1045,'Pop','Duran Duran','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1046,'Hip Hop','Enya','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1047,'Jazz','Elvis Presley','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1048,'Techno','George Michael','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1049,'Pop','Calvin Harris','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1050,'Rock','Def Leppard','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1051,'Techno','Paul Weller','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1052,'Indie Rock','Moby','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1053,'EDM','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1054,'Hip Hop','Perry Como','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1055,'Jazz','Erasure','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1056,'Rock','Enigma','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1057,'Pop','Dr. Dre','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1058,'Rock','Vangelis','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1059,'Indie Rock','Madness','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1060,'Rock','Simon & Garfunkel','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1061,'Indie Rock','The Beatles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1062,'EDM','Justin Timberlake','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1063,'Jazz','Kasabian','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1064,'Techno','Ariana Grande','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1065,'Rock','Maroon 5','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1066,'EDM','Elton John','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1067,'Rock','George Michael','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1068,'Rock','Phil Collins','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1069,'Pop','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1070,'EDM','Rag’n’Bone Man','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1071,'Pop','Pink Floyd','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1072,'Jazz','INXS','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1073,'Jazz','Manic Street Preachers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1074,'Rock','Britney Spears','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1075,'Pop','Leona Lewis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1076,'Blues','Jessie J','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1077,'Rock','Jake Bugg','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1078,'EDM','Sia','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1079,'Rock','Whitney Houston','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1080,'Techno','UB40','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1081,'Rock','Michael Jackson','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1082,'Hip Hop','Duffy','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1083,'Metal','Chase & Status','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1084,'Indie Rock','Drake','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1085,'Blues','Eric Clapton','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1086,'Pop','Natalie Imbruglia','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1087,'Rock','Kaiser Chiefs','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1088,'Pop','Biffy Clyro','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1089,'Pop','Panic! at the Disco','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1090,'Hip Hop','John Lennon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1091,'Indie Rock','Elton John','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1092,'Rock','Electric Light Orchestra','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1093,'Pop','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1094,'EDM','Fatboy Slim','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1095,'Rock','Katie Melua','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1096,'Indie Rock','The Kooks','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1097,'Jazz','Gregory Porter','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1098,'Rock','J Hus','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1099,'Rock','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1100,'Blues','The Prodigy','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1101,'Pop','U2','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1102,'Hip Hop','Ben Howard','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1103,'Techno','Bee Gees','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1104,'Pop','Robbie Williams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1105,'Jazz','Dido','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1106,'Rock','The Script','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1107,'Metal','David Bowie','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1108,'Jazz','Amy Winehouse','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1109,'Pop','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1110,'Rock','Elbow','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1111,'Indie Rock','Original Cast','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1112,'Pop','Ellie Goulding','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1113,'Jazz','George Mitchell Minstrels','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1114,'Metal','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1115,'Metal','Bon Jovi','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1116,'Blues','Paolo Nutini','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1117,'Rock','Linkin Park','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1118,'Jazz','Eurythmics','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1119,'Rock','Celine Dion','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1120,'Pop','The Corrs','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1121,'Pop','Lana Del Rey','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1122,'Rock','ZZ Top','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1123,'Rock','Catfish and the Bottlemen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1124,'EDM','Katy Perry','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1125,'Metal','The Stone Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1126,'Blues','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1127,'Indie Rock','The Carpenters','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1128,'Rock','Simply Red','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1129,'Indie Rock','The Beautiful South','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1130,'Indie Rock','Emeli Sandé','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1131,'Pop','Bruce Springsteen','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1132,'Rock','The Killers','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1133,'Metal','Adele','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1134,'Pop','Eminem','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1135,'Rock','Travis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1136,'Metal','Robbie Williams','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1137,'Pop','Robbie Williams','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1138,'Jazz','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1139,'Pop','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1140,'Metal','Take That','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1141,'Hip Hop','Ed Sheeran','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1142,'Techno','Garbage','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1143,'Pop','Scissor Sisters','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1144,'Rock','Paul McCartney and Wings','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1145,'Jazz','ABBA','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1146,'Rock','Barbra Streisand','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1147,'Pop','Kate Bush','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1148,'Pop','Massive Attack','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1149,'Indie Rock','Keane','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1150,'Rock','James Blunt','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1151,'Jazz','Led Zeppelin','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1152,'Metal','Carole King','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1153,'Rock','Lionel Richie','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1154,'Pop','Celine Dion','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1155,'Jazz','M People','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1156,'Rock','Beyoncé','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1157,'Blues','Rod Stewart','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1158,'EDM','Barry White','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1159,'Rock','Massive Attack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1160,'Metal','One Direction','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1161,'Metal','Bastille','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1162,'EDM','U2','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1163,'EDM','Plan B','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1164,'EDM','Justin Bieber','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1165,'Hip Hop','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1166,'Jazz','Green Day','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1167,'Metal','The Killers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1168,'Pop','Imagine Dragons','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1169,'Rock','Post Malone','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1170,'Rock','Florence and the Machine','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1171,'Hip Hop','Coldplay','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1172,'Indie Rock','Rod Stewart','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1173,'Techno','Bon Jovi','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1174,'Pop','Michael Jackson','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1175,'Metal','Tina Turner','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1176,'Hip Hop','Michael Bublé','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1177,'Hip Hop','Eagles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1178,'Indie Rock','Paolo Nutini','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1179,'Hip Hop','Rihanna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1180,'Jazz','Phil Collins','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1181,'Metal','Phil Collins','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1182,'Pop','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1183,'Indie Rock','Lighthouse Family','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1184,'Techno','David Gray','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1185,'Rock','Lady Gaga','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1186,'Hip Hop','Van Morrison','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1187,'Indie Rock','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1188,'Rock','Red Hot Chili Peppers','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1189,'Jazz','UB40','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1190,'EDM','Kings of Leon','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1191,'Hip Hop','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1192,'Jazz','The Corrs','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1193,'Rock','Red Hot Chili Peppers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1194,'Rock','The Beatles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1195,'Rock','David Bowie','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1196,'Metal','Simply Red','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1197,'Pop','Stereophonics','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1198,'Hip Hop','The Verve','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1199,'Rock','Shania Twain','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1200,'Metal','Paul Simon','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1201,'Hip Hop','George Ezra','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1202,'Pop','Taylor Swift','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1203,'Indie Rock','The 1975','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1204,'Techno','Original Broadway Cast','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1205,'Hip Hop','Eva Cassidy','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1206,'Rock','Buddy Holly','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1207,'Rock','Bon Jovi','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1208,'Hip Hop','Bruno Mars','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1209,'EDM','P!nk','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1210,'Rock','Lionel Richie','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1211,'Blues','Madonna','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1212,'Blues','Norah Jones','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1213,'Indie Rock','Little Mix','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1214,'Rock','The Beach Boys','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1215,'Blues','Barry Manilow','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1216,'Hip Hop','Snow Patrol','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1217,'EDM','Adele','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1218,'Rock','Tina Turner','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1219,'Blues','Coldplay','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1220,'Hip Hop','Michael Bublé','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1221,'Blues','Queen','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1222,'Blues','ABBA','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1223,'Rock','Bob Marley and the Wailers','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1224,'Techno','Fleetwood Mac','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1225,'Hip Hop','Pink Floyd','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1226,'Pop','Meat Loaf','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1227,'Blues','Michael Jackson','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1228,'Indie Rock','Oasis','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1229,'Indie Rock','Amy Winehouse','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1230,'Rock','Eminem','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1231,'Metal','Original Soundtrack','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1232,'EDM','Fleetwood Mac','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1233,'Pop','Madonna','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1234,'EDM','Foo Fighters','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1235,'Jazz','Oasis','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1236,'Metal','Nirvana','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1237,'Blues','Simon & Garfunkel','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1238,'Metal','Simon & Garfunkel','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1239,'Indie Rock','Oasis','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1240,'Pop','Arctic Monkeys','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1241,'Rock','Guns N’ Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1242,'EDM','Original Soundtrack','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1243,'Hip Hop','Whitney Houston','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1244,'Pop','Phil Collins','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1245,'Pop','Tracy Chapman','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1246,'Rock','Ed Sheeran','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1247,'Pop','Mike Oldfield','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1248,'Hip Hop','Michael Jackson','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1249,'Hip Hop','Guns N’ Roses','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1250,'Jazz','The Beatles','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1251,'Pop','Dire Straits','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1252,'Blues','Adele','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1253,'Indie Rock','Sam Smith','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1254,'Indie Rock','Arctic Monkeys','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1255,'Pop','Queen','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1256,'Hip Hop','Dire Straits','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1257,'Jazz','The Killers','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1258,'Hip Hop','R.E.M.','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1259,'Pop','Frank Sinatra','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1260,'Rock','The Beatles','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1261,'Blues','Michael Jackson','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1262,'Indie Rock','Alanis Morissette','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1263,'Techno','Take That','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1264,'Jazz','Mumford & Sons','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1265,'Pop','R.E.M.','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1266,'Metal','Adele','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1267,'Pop','The Beatles','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1268,'EDM','Jess Glynne','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1269,'EDM','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1270,'Jazz','Original Soundtrack','MP3');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1271,'Pop','Radiohead','CD');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1272,'Rock','U2','Vinil');
INSERT INTO FNAC.Musica (id_artigo, genero_musical, artista, formato) VALUES (1273,'Rock','Dire Straits','CD');