-- INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao)
Use FNAC;
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (1,'To Kill a Mockingbird','Livro',10.8,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (2,'Pride and Prejudice','Livro',13,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (3,'Anne Frank: The Diary of a Young Girl','Livro',15,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (4,'1984','Livro',9.6,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (5,'Harry Potter and the Sorcerer’s Stone','Livro',17.5,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (6,'The Lord of the Rings','Livro',13.9,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (7,'The Great Gatsby','Livro',11,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (8,'Charlotte’s Web','Livro',16.9,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (9,'Little Women','Livro',13.9,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (10,'The Hobbit','Livro',14,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (11,'Fahrenheit 451','Livro',13.8,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (12,'Jane Eyre','Livro',13.7,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (13,'Gone With the Wind','Livro',9.2,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (14,'Animal Farm','Livro',13.6,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (15,'The Catcher in the Rye','Livro',13.3,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (16,'The Adventures of Huckleberry Finn','Livro',11.5,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (17,'The Help','Livro',10.3,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (18,'The Grapes of Wrath','Livro',11.3,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (19,'The Lion, the Witch and the Wardrobe','Livro',15.5,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (20,'The Hunger Games','Livro',15.7,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (21,'The Book Thief','Livro',16.7,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (22,'Lord of the Flies','Livro',14.2,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (23,'The Kite Runner','Livro',17.7,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (24,'Night','Livro',17.3,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (25,'Hamlet','Livro',15.3,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (26,'A Tale of Two Cities','Livro',10.5,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (27,'A Wrinkle in Time','Livro',9.9,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (28,'The Hitchhiker’s Guide to the Galaxy','Livro',11.5,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (29,'A Christmas Carol','Livro',12.4,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (30,'Of Mice and Men','Livro',17.1,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (31,'The Secret Garden','Livro',11.2,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (32,'Romeo and Juliet','Livro',13.6,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (33,'The Handmaid’s Tale','Livro',12.8,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (34,'Brave New World','Livro',14.7,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (35,'The Little Prince','Livro',12.6,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (36,'Where the Sidewalk Ends','Livro',14.5,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (37,'Wuthering Heights','Livro',15,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (38,'The Giver','Livro',13.2,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (39,'Anne of Green Gables','Livro',13.1,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (40,'Macbeth','Livro',12.1,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (41,'The Adventures of Tom Sawyer','Livro',13.2,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (42,'Harry Potter and the Deathly Hallows','Livro',17.5,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (43,'Frankenstein','Livro',17.4,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (44,'The Holy Bible: New King James Version','Livro',9.7,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (45,'The Girl with the Dragon Tattoo','Livro',16.2,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (46,'The Count of Monte Cristo','Livro',13.3,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (47,'The Fault in Our Stars','Livro',14.5,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (48,'The Color Purple','Livro',15,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (49,'East of Eden','Livro',15.3,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (50,'A Tree Grows in Brooklyn','Livro',16,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (51,'Catch-22','Livro',13.9,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (52,'In Cold Blood','Livro',16.6,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (53,'The Stand','Livro',13.3,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (54,'Alice in Wonderland','Livro',10.2,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (55,'Watership Down','Livro',17.6,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (56,'Anna Karenina','Livro',16.7,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (57,'Ender’s Game','Livro',15.6,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (58,'Great Expectations','Livro',16.8,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (59,'Rebecca','Livro',9,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (60,'Memoirs of a Geisha: A Novel','Livro',9.1,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (61,'The Adventures of Sherlock Holmes','Livro',12,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (62,'Harry Potter and the Prisoner of Azkaban','Livro',13.7,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (63,'The Old Man and the Sea','Livro',14.7,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (64,'Game of Thrones (A Song of Ice and Fire Book)','Livro',17.9,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (65,'The Princess Bride','Livro',15.9,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (66,'Charlie and the Chocolate Factory','Livro',12.2,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (67,'Life of Pi','Livro',11.1,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (68,'Skellig','Livro',13.2,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (69,'Peter Pan','Livro',10.2,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (70,'Carrie’s War','Livro',15.9,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (71,'Hacker','Livro',15.4,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (72,'Cottrell Millions','Livro',13.9,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (73,'Young Samurai series','Livro',10.2,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (74,'The Secret Garden','Livro',9.3,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (75,'A Little Princess','Livro',11,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (76,'Alice’s Adventures in Wonderland','Livro',12.7,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (77,'Through the Looking Glass Classics','Livro',13.4,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (78,'Dizzy','Livro',16.7,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (79,'Looking Glass Girl','Livro',12,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (80,'Artemis Fowl series','Livro',13.8,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (81,'What Katy Did','Livro',17.6,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (82,'Heartbeat','Livro',9.2,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (83,'The Demon Headmaster','Livro',11.8,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (84,'After Tomorrow','Livro',17.9,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (85,'Charlie and the Chocolate','Livro',10.6,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (86,'Granny was a Buffer Girl','Livro',14.8,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (87,'Street Child','Livro',17.7,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (88,'The London Eye Mystery','Livro',9.5,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (89,'Madame Doubtfire','Livro',16,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (90,'War Game','Livro',14.7,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (91,'The Thief Lord','Livro',17.5,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (92,'I Coriander','Livro',11.8,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (93,'The Wind in the Willows','Livro',16.6,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (94,'Hoot','Livro',17.8,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (95,'I am David','Livro',10,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (96,'Alex Rider series','Livro',12.7,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (97,'Journey to the River Sea','Livro',15.2,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (98,'When Hitler Stole Pink Rabbit','Livro',11.3,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (99,'Young Sherlock Holmes series','Livro',10.8,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (100,'Kiss the Dust','Livro',11.1,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (101,'The Roman Mysteries series','Livro',9.2,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (102,'Chronicles of Narnia series','Livro',15.1,0000,5.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (103,'The Borrowers','Livro',15.5,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (104,'Aquilla','Livro',14.6,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (105,'Wonder','Livro',11.3,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (106,'Swallows and Amazons','Livro',15.2,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (107,'Percy Jackson series','Livro',10.5,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (108,'Kiss of Death','Livro',14,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (109,'Harry Potter series','Livro',17.8,0000,5.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (110,'Holes','Livro',14.2,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (111,'Five Children on the Western Front','Livro',12.4,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (112,'Timeriders series','Livro',13.2,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (113,'She is not Invisible','Livro',9,0000,4.9);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (114,'Black Beauty','Livro',14.5,0000,4.3);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (115,'The Hundred and One Dalmatians','Livro',9.9,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (116,'A Series of Unfortunate Events','Livro',16.6,0000,5.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (117,'Ballet Shoes','Livro',17.4,0000,4.6);
INSERT INTO FNAC.Artigo (id_artigo,titulo,tipo,preco,ano,classificacao) VALUES (118,'The Machine Gunners','Livro',16.9,0000,4.6);